# Generated by Django 5.1.2 on 2024-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='client/profile/avatar/default_avatar.png', upload_to='profile/avatar/'),
        ),
    ]
