# Generated by Django 5.1.2 on 2024-11-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='client/profile/avatar/default_avatar.png', upload_to='profile/avatar/'),
        ),
    ]
