# Generated by Django 5.1.2 on 2024-11-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='researcher',
            new_name='consultant',
        ),
    ]
