# Generated by Django 5.1.2 on 2024-11-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_researcher_user_consultant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
