# Generated by Django 5.1.2 on 2024-11-18 15:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='شرکت ارسال کننده')),
                ('cost', models.IntegerField(verbose_name='هزینه ارسال')),
                ('status', models.BooleanField(choices=[(1, 'در دسترس'), (0, 'خارج ازدسترس')], default=1, verbose_name='وضعیت سرویس')),
            ],
            options={
                'verbose_name': 'شرکت ارسال کننده ',
                'verbose_name_plural': 'شرکت های ارسال کننده ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_ordered', models.TextField(blank=True, verbose_name='سفارشات مشتری')),
                ('products_type_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد انواع محصول')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('details', models.TextField(blank=True, verbose_name='توضیحات')),
                ('total_cost', models.CharField(max_length=20, null=True, verbose_name='جمع سفارش')),
                ('register_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان ثبت کالا')),
                ('status', models.BooleanField(choices=[(1, 'پرداخت شده'), (0, 'پرداخت نشده')], default=0, verbose_name='وضعیت پرداخت')),
                ('bill_id', models.CharField(blank=True, max_length=100, verbose_name='شماره رسید')),
                ('delivery', models.BooleanField(choices=[(0, 'تحویل نشده'), (1, 'تحویل شده')], default=0, verbose_name='وضعیت تحویل به پست')),
                ('post_id', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری مرسوله')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('deliver_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.delivery', verbose_name='شرکت تحویل دهنده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('sub_title', models.CharField(blank=True, max_length=50, verbose_name='زیر عنوان')),
                ('caption', models.TextField(verbose_name='توضیحات')),
                ('price', models.CharField(max_length=20, verbose_name='قیمت')),
                ('maintenance', models.IntegerField(default=1000, verbose_name='موجودی محصول')),
                ('register_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان ثبت کالا')),
                ('status', models.BooleanField(choices=[(1, 'موجود'), (0, 'ناموجود')], default=1, verbose_name='وضعیت محصول')),
                ('offer', models.BooleanField(default=False, verbose_name='تخفیف محصول')),
                ('discount', models.CharField(default='0', max_length=20, verbose_name='درصد تخقیف محصول')),
                ('image_main', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر اصلی')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر اول')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر دوم')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر سوم')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
