# Generated by Django 5.1.2 on 2024-11-18 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultant_prescript', to=settings.AUTH_USER_MODEL)),
                ('drugs', models.ManyToManyField(to='store.product')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه ها',
            },
        ),
    ]
